osx_image: xcode8.2
language: generic
matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      dist: trusty
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./ci/setup_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew brew install carthage; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then carthage bootstrap; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . rake test:swiftpm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rake; rake test:swiftpm; fi
